### ISSUE TITLE
Documento de Arquitetura de Software

### ISSUE THREAD

**Issue by JonathasSL** [JonathasSL/SmartParking#5]
- [x] Requisitos funcionais e não funcionais
* Modelagem e projeto arquitetural básico 
  - [x] Diagrama de contexto - [Referencia](https://dicaspmp.wordpress.com/2015/03/13/diagramas-de-contexto/)

[Templates](https://drive.google.com/drive/folders/1y9w_oMMA_LBfslXfsrKZKevwPmoWXMhw?usp=sharing)

**Comment by H1bertto** [comment]
OK

**Comment by H1bertto** [comment]
[Documento de Arquitetura de Software](https://drive.google.com/file/d/18H40Nk2mWVhYavYqG17MFZLZFmpf56To/view?usp=sharing)
